version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map port 80 (Nginx) to port 3000 on your machine
    volumes:
      - ./frontend:/app  # Mount the frontend directory for development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Map port 8000 (Django) to port 8000 on your machine
    volumes:
      - ./backend:/app  # Mount the backend directory for development
    environment:
      - DEBUG=1