"""add-cache-model-llm

Revision ID: 9e1863d1656f
Revises: a2bd12ad6f60
Create Date: 2025-02-10 16:14:33.713338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1863d1656f'
down_revision: Union[str, None] = 'a2bd12ad6f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('path_store_cache_model_main', sa.String(), nullable=True))
    op.create_index(op.f('ix_settings_path_store_cache_model_main'), 'settings', ['path_store_cache_model_main'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_path_store_cache_model_main'), table_name='settings')
    op.drop_column('settings', 'path_store_cache_model_main')
    # ### end Alembic commands ###
