"""Add-Setting

Revision ID: a2bd12ad6f60
Revises: 4b1abf1d900f
Create Date: 2025-02-06 12:43:55.550283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2bd12ad6f60'
down_revision: Union[str, None] = '4b1abf1d900f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('path_store_name_main', sa.String(), nullable=True),
    sa.Column('notification_enable', sa.Boolean(), nullable=True),
    sa.Column('log_enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_index(op.f('ix_settings_log_enable'), 'settings', ['log_enable'], unique=False)
    op.create_index(op.f('ix_settings_notification_enable'), 'settings', ['notification_enable'], unique=False)
    op.create_index(op.f('ix_settings_path_store_name_main'), 'settings', ['path_store_name_main'], unique=False)
    op.create_index(op.f('ix_settings_setting_id'), 'settings', ['setting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_setting_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_path_store_name_main'), table_name='settings')
    op.drop_index(op.f('ix_settings_notification_enable'), table_name='settings')
    op.drop_index(op.f('ix_settings_log_enable'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
