"""Reinitialize migration

Revision ID: eb3949f8dd2b
Revises: 167894a94615
Create Date: 2025-02-24 13:38:39.146321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3949f8dd2b'
down_revision: Union[str, None] = '167894a94615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_path_models',
    sa.Column('path_download_id', sa.Integer(), nullable=False),
    sa.Column('path_download_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('path_download_id')
    )
    op.create_index(op.f('ix_download_path_models_path_download_id'), 'download_path_models', ['path_download_id'], unique=False)
    op.create_index(op.f('ix_download_path_models_path_download_name'), 'download_path_models', ['path_download_name'], unique=False)
    op.create_table('models',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index(op.f('ix_models_model_id'), 'models', ['model_id'], unique=False)
    op.create_index(op.f('ix_models_model_name'), 'models', ['model_name'], unique=False)
    op.create_index(op.f('ix_models_path'), 'models', ['path'], unique=True)
    op.create_index(op.f('ix_models_size'), 'models', ['size'], unique=False)
    op.create_index(op.f('ix_models_unit'), 'models', ['unit'], unique=False)
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('path_store_name_main', sa.String(), nullable=True),
    sa.Column('path_store_cache_model_main', sa.String(), nullable=True),
    sa.Column('notification_enable', sa.Boolean(), nullable=True),
    sa.Column('log_enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('setting_id')
    )
    op.create_index(op.f('ix_settings_log_enable'), 'settings', ['log_enable'], unique=False)
    op.create_index(op.f('ix_settings_notification_enable'), 'settings', ['notification_enable'], unique=False)
    op.create_index(op.f('ix_settings_path_store_cache_model_main'), 'settings', ['path_store_cache_model_main'], unique=False)
    op.create_index(op.f('ix_settings_path_store_name_main'), 'settings', ['path_store_name_main'], unique=False)
    op.create_index(op.f('ix_settings_setting_id'), 'settings', ['setting_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_setting_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_path_store_name_main'), table_name='settings')
    op.drop_index(op.f('ix_settings_path_store_cache_model_main'), table_name='settings')
    op.drop_index(op.f('ix_settings_notification_enable'), table_name='settings')
    op.drop_index(op.f('ix_settings_log_enable'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_models_unit'), table_name='models')
    op.drop_index(op.f('ix_models_size'), table_name='models')
    op.drop_index(op.f('ix_models_path'), table_name='models')
    op.drop_index(op.f('ix_models_model_name'), table_name='models')
    op.drop_index(op.f('ix_models_model_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_download_path_models_path_download_name'), table_name='download_path_models')
    op.drop_index(op.f('ix_download_path_models_path_download_id'), table_name='download_path_models')
    op.drop_table('download_path_models')
    # ### end Alembic commands ###
